"""add timeout/retry to TestCase

Revision ID: 1f780a7100fc
Revises: a0142297cd80
Create Date: 2026-06-02 03:38:02.144380

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1f780a7100fc"
down_revision = "a0142297cd80"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("test_case", schema=None) as batch_op:
        batch_op.add_column(sa.Column("timeout", sa.Integer(), nullable=True, comment="请求超时时间（秒）"))
        batch_op.add_column(sa.Column("retry", sa.Integer(), nullable=True, comment="失败重试次数"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("test_case", schema=None) as batch_op:
        batch_op.drop_column("retry")
        batch_op.drop_column("timeout")

    # ### end Alembic commands ###
