"""add ApiCoverage

Revision ID: 32c84a192460
Revises: 1f780a7100fc
Create Date: 2026-06-02 04:02:07.920997

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "32c84a192460"
down_revision = "1f780a7100fc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_coverage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("method", sa.String(length=10), nullable=False, comment="HTTP 方法"),
        sa.Column("path", sa.String(length=500), nullable=False, comment="URL 路径"),
        sa.Column("summary", sa.String(length=200), nullable=True, comment="接口描述（从 Swagger 导入）"),
        sa.Column("is_covered", sa.Boolean(), nullable=True, comment="是否有测试覆盖"),
        sa.Column("covered_by", sa.Integer(), nullable=True, comment="最后覆盖人"),
        sa.Column("covered_time", sa.DateTime(), nullable=True, comment="最后覆盖时间"),
        sa.Column("create_time", sa.DateTime(), nullable=True, comment="导入时间"),
        sa.ForeignKeyConstraint(["covered_by"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("api_coverage", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_api_coverage_is_covered"), ["is_covered"], unique=False)
        batch_op.create_index(batch_op.f("ix_api_coverage_path"), ["path"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("api_coverage", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_api_coverage_path"))
        batch_op.drop_index(batch_op.f("ix_api_coverage_is_covered"))

    op.drop_table("api_coverage")
    # ### end Alembic commands ###
