"""add extra to PerformanceReport

Revision ID: 3f992570278a
Revises: 7dfa470f5529
Create Date: 2026-05-31 23:04:47.756207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f992570278a'
down_revision = '7dfa470f5529'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performance_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extra', sa.Text(), nullable=True, comment='扩展数据（JSON，如每秒QPS序列）'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performance_report', schema=None) as batch_op:
        batch_op.drop_column('extra')

    # ### end Alembic commands ###
