"""add tags to cases

Revision ID: 4e38abe6bd09
Revises: 32c84a192460
Create Date: 2026-06-02 05:10:23.042642

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4e38abe6bd09"
down_revision = "32c84a192460"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("performance_case", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "tags", sa.String(length=500), nullable=True, comment="用例标签，逗号分隔，如 smoke,regression,critical"
            )
        )
        batch_op.create_index(batch_op.f("ix_performance_case_tags"), ["tags"], unique=False)

    with op.batch_alter_table("test_case", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "tags", sa.String(length=500), nullable=True, comment="用例标签，逗号分隔，如 smoke,regression,critical"
            )
        )
        batch_op.create_index(batch_op.f("ix_test_case_tags"), ["tags"], unique=False)

    with op.batch_alter_table("ui_case", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "tags", sa.String(length=500), nullable=True, comment="用例标签，逗号分隔，如 smoke,regression,critical"
            )
        )
        batch_op.create_index(batch_op.f("ix_ui_case_tags"), ["tags"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ui_case", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ui_case_tags"))
        batch_op.drop_column("tags")

    with op.batch_alter_table("test_case", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_test_case_tags"))
        batch_op.drop_column("tags")

    with op.batch_alter_table("performance_case", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_performance_case_tags"))
        batch_op.drop_column("tags")

    # ### end Alembic commands ###
