"""add_environment_envid

Revision ID: 7387db0d761e
Revises: 9fe14fa34fc5
Create Date: 2026-06-25 20:44:54.668315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7387db0d761e'
down_revision = '9fe14fa34fc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('environment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='环境名称，如 开发环境/测试环境/生产环境'),
    sa.Column('base_url', sa.String(length=500), nullable=False, comment='环境基地址，如 http://dev-server:8080'),
    sa.Column('headers', sa.Text(), nullable=True, comment='全局请求头，JSON 对象'),
    sa.Column('variables', sa.Text(), nullable=True, comment="环境变量，JSON 对象，如 {'token': 'xxx'}"),
    sa.Column('is_default', sa.Boolean(), nullable=True, comment='是否为默认环境'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('performance_case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('env_id', sa.Integer(), nullable=True, comment='所属环境ID'))
        batch_op.create_index(batch_op.f('ix_performance_case_env_id'), ['env_id'], unique=False)
        batch_op.create_foreign_key(None, 'environment', ['env_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('test_case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('env_id', sa.Integer(), nullable=True, comment='所属环境ID'))
        batch_op.create_index(batch_op.f('ix_test_case_env_id'), ['env_id'], unique=False)
        batch_op.create_foreign_key(None, 'environment', ['env_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('ui_case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('env_id', sa.Integer(), nullable=True, comment='所属环境ID'))
        batch_op.create_index(batch_op.f('ix_ui_case_env_id'), ['env_id'], unique=False)
        batch_op.create_foreign_key(None, 'environment', ['env_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ui_case', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_ui_case_env_id'))
        batch_op.drop_column('env_id')

    with op.batch_alter_table('test_case', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_test_case_env_id'))
        batch_op.drop_column('env_id')

    with op.batch_alter_table('performance_case', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_performance_case_env_id'))
        batch_op.drop_column('env_id')

    op.drop_table('environment')
    # ### end Alembic commands ###
