"""add ramp_steps and steady_duration

Revision ID: 7dfa470f5529
Revises: 91f48fb57b9f
Create Date: 2026-05-31 22:56:30.096798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dfa470f5529'
down_revision = '91f48fb57b9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performance_case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ramp_steps', sa.Integer(), nullable=True, comment='阶梯加压步数（1=直接加压，5=分5步到达目标并发）'))
        batch_op.add_column(sa.Column('steady_duration', sa.Integer(), nullable=True, comment='稳态持续时间（秒，0=不持久化）'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performance_case', schema=None) as batch_op:
        batch_op.drop_column('steady_duration')
        batch_op.drop_column('ramp_steps')

    # ### end Alembic commands ###
