"""full baseline

Revision ID: 91f48fb57b9f
Revises: 
Create Date: 2026-05-31 06:48:34.093645

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "91f48fb57b9f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("password_hash", sa.String(length=256), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=True),
        sa.Column("role", sa.String(length=20), nullable=True),
        sa.Column("create_time", sa.DateTime(), nullable=True),
        sa.Column("update_time", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_role"), ["role"], unique=False)

    op.create_table(
        "ai_agent_task",
        sa.Column("id", sa.Integer(), nullable=False, comment="主键ID"),
        sa.Column("task_type", sa.String(length=32), nullable=False, comment="任务类型"),
        sa.Column("input_content", sa.Text(), nullable=False, comment="用户输入内容"),
        sa.Column("output_result", sa.Text(), nullable=True, comment="AI输出结果"),
        sa.Column("creator_id", sa.Integer(), nullable=True, comment="创建人ID"),
        sa.Column("create_time", sa.DateTime(), nullable=True, comment="创建时间"),
        sa.Column("update_time", sa.DateTime(), nullable=True, comment="更新时间"),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ai_agent_task", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ai_agent_task_creator_id"), ["creator_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_ai_agent_task_task_type"), ["task_type"], unique=False)

    op.create_table(
        "async_task",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "task_type",
            sa.String(length=32),
            nullable=False,
            comment="任务类型: ai_generate / batch_run / ui_run / perf_run",
        ),
        sa.Column("status", sa.String(length=16), nullable=True, comment="pending / running / success / failed"),
        sa.Column("result", sa.Text(), nullable=True, comment="任务结果（JSON）"),
        sa.Column("error_msg", sa.Text(), nullable=True, comment="错误信息"),
        sa.Column("creator_id", sa.Integer(), nullable=True, comment="创建者ID"),
        sa.Column("create_time", sa.DateTime(), nullable=True, comment="创建时间"),
        sa.Column("finish_time", sa.DateTime(), nullable=True, comment="完成时间"),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("async_task", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_async_task_creator_id"), ["creator_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_async_task_status"), ["status"], unique=False)

    op.create_table(
        "batch_task",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("total", sa.Integer(), nullable=True, comment="总用例数"),
        sa.Column("passed", sa.Integer(), nullable=True, comment="通过数"),
        sa.Column("failed", sa.Integer(), nullable=True, comment="失败数"),
        sa.Column("creator_id", sa.Integer(), nullable=True, comment="创建者"),
        sa.Column("create_time", sa.DateTime(), nullable=True, comment="创建时间"),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "performance_case",
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.Column("method", sa.String(length=10), nullable=True),
        sa.Column("headers", sa.Text(), nullable=True),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("concurrency", sa.Integer(), nullable=True),
        sa.Column("total", sa.Integer(), nullable=True),
        sa.Column("creator_id", sa.Integer(), nullable=True),
        sa.Column("update_time", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("create_time", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("performance_case", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_performance_case_create_time"), ["create_time"], unique=False)
        batch_op.create_index(batch_op.f("ix_performance_case_creator_id"), ["creator_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_performance_case_name"), ["name"], unique=False)

    op.create_table(
        "sys_operation_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True, comment="操作用户ID（admin为超级管理员）"),
        sa.Column("username", sa.String(length=50), nullable=False, comment="操作用户名"),
        sa.Column(
            "operation",
            sa.String(length=50),
            nullable=False,
            comment="操作类型：login/delete_user/change_role/add_case等",
        ),
        sa.Column("ip", sa.String(length=50), nullable=True, comment="操作IP地址"),
        sa.Column("operate_time", sa.DateTime(), nullable=True, comment="操作时间"),
        sa.Column("detail", sa.Text(), nullable=True, comment="操作详情（如：删除用户ID=1，修改角色为admin等）"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sys_operation_log", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sys_operation_log_operate_time"), ["operate_time"], unique=False)
        batch_op.create_index(batch_op.f("ix_sys_operation_log_operation"), ["operation"], unique=False)
        batch_op.create_index(batch_op.f("ix_sys_operation_log_user_id"), ["user_id"], unique=False)

    op.create_table(
        "test_case",
        sa.Column("module", sa.String(length=50), nullable=True, comment="所属模块"),
        sa.Column("method", sa.String(length=10), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.Column("headers", sa.Text(), nullable=True),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("expect", sa.String(length=200), nullable=True),
        sa.Column("extract_var", sa.String(length=200), nullable=True, comment="后置提取：格式如 token=$.args.token"),
        sa.Column("creator_id", sa.Integer(), nullable=True),
        sa.Column("update_time", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("create_time", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("test_case", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_test_case_create_time"), ["create_time"], unique=False)
        batch_op.create_index(batch_op.f("ix_test_case_creator_id"), ["creator_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_test_case_module"), ["module"], unique=False)
        batch_op.create_index(batch_op.f("ix_test_case_name"), ["name"], unique=False)

    op.create_table(
        "test_task",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("cron_expr", sa.String(length=50), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("creator_id", sa.Integer(), nullable=True),
        sa.Column("create_time", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ui_case",
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.Column("steps", sa.Text(), nullable=True),
        sa.Column("loc_type", sa.String(length=20), nullable=True, comment="元素定位方式：id/xpath/css"),
        sa.Column("loc_value", sa.String(length=500), nullable=True, comment="元素定位值"),
        sa.Column("screenshot_path", sa.String(length=500), nullable=True, comment="测试截图路径"),
        sa.Column("creator_id", sa.Integer(), nullable=True),
        sa.Column("update_time", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("create_time", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ui_case", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ui_case_create_time"), ["create_time"], unique=False)
        batch_op.create_index(batch_op.f("ix_ui_case_creator_id"), ["creator_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_ui_case_name"), ["name"], unique=False)

    op.create_table(
        "batch_result",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("batch_id", sa.Integer(), nullable=True, comment="所属批次"),
        sa.Column("case_id", sa.Integer(), nullable=True, comment="用例ID"),
        sa.Column("case_name", sa.String(length=100), nullable=True, comment="用例名称"),
        sa.Column("status", sa.String(length=20), nullable=True, comment="pass / fail / error"),
        sa.Column("cost_time", sa.Float(), nullable=True, comment="耗时（秒）"),
        sa.Column("response_code", sa.Integer(), nullable=True, comment="响应状态码"),
        sa.Column("error_msg", sa.Text(), nullable=True, comment="错误信息"),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["batch_task.id"],
        ),
        sa.ForeignKeyConstraint(["case_id"], ["test_case.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "performance_report",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("case_id", sa.Integer(), nullable=True),
        sa.Column("case_name", sa.String(length=100), nullable=True),
        sa.Column("concurrency", sa.Integer(), nullable=True),
        sa.Column("total", sa.Integer(), nullable=True),
        sa.Column("success", sa.Integer(), nullable=True),
        sa.Column("fail", sa.Integer(), nullable=True),
        sa.Column("qps", sa.Float(), nullable=True),
        sa.Column("avg_time", sa.Float(), nullable=True),
        sa.Column("min_time", sa.Float(), nullable=True),
        sa.Column("max_time", sa.Float(), nullable=True),
        sa.Column("create_time", sa.DateTime(), nullable=True),
        sa.Column("p90", sa.Float(), nullable=True),
        sa.Column("p99", sa.Float(), nullable=True),
        sa.Column("success_rate", sa.Float(), nullable=True),
        sa.Column("is_local", sa.Boolean(), nullable=True, comment="是否本机压测（可能导致数据失真）"),
        sa.ForeignKeyConstraint(["case_id"], ["performance_case.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("performance_report", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_performance_report_case_id"), ["case_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_performance_report_create_time"), ["create_time"], unique=False)

    op.create_table(
        "task_case_association",
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("case_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["test_case.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["task_id"], ["test_task.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("task_id", "case_id"),
    )
    op.create_table(
        "test_report",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("case_id", sa.Integer(), nullable=True),
        sa.Column("case_name", sa.String(length=100), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("cost_time", sa.Float(), nullable=True),
        sa.Column("response_code", sa.Integer(), nullable=True),
        sa.Column("response_body", sa.Text(), nullable=True),
        sa.Column("error_msg", sa.Text(), nullable=True),
        sa.Column("create_time", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["case_id"], ["test_case.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("test_report", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_test_report_case_id"), ["case_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_test_report_create_time"), ["create_time"], unique=False)
        batch_op.create_index(batch_op.f("ix_test_report_status"), ["status"], unique=False)

    op.create_table(
        "ui_report",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("case_id", sa.Integer(), nullable=True),
        sa.Column("case_name", sa.String(length=100), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("cost_time", sa.Float(), nullable=True),
        sa.Column("error_msg", sa.Text(), nullable=True),
        sa.Column("create_time", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["case_id"], ["ui_case.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ui_report", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ui_report_case_id"), ["case_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_ui_report_create_time"), ["create_time"], unique=False)
        batch_op.create_index(batch_op.f("ix_ui_report_status"), ["status"], unique=False)

    op.create_table(
        "performance_detail",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("report_id", sa.Integer(), nullable=True, comment="关联压测报告ID"),
        sa.Column("url", sa.String(length=500), nullable=True, comment="请求URL"),
        sa.Column("request_time", sa.Float(), nullable=True, comment="本次请求耗时(ms)"),
        sa.Column("status_code", sa.Integer(), nullable=True, comment="HTTP 状态码"),
        sa.Column("create_time", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["report_id"], ["performance_report.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("performance_detail", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_performance_detail_report_id"), ["report_id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("performance_detail", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_performance_detail_report_id"))

    op.drop_table("performance_detail")
    with op.batch_alter_table("ui_report", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ui_report_status"))
        batch_op.drop_index(batch_op.f("ix_ui_report_create_time"))
        batch_op.drop_index(batch_op.f("ix_ui_report_case_id"))

    op.drop_table("ui_report")
    with op.batch_alter_table("test_report", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_test_report_status"))
        batch_op.drop_index(batch_op.f("ix_test_report_create_time"))
        batch_op.drop_index(batch_op.f("ix_test_report_case_id"))

    op.drop_table("test_report")
    op.drop_table("task_case_association")
    with op.batch_alter_table("performance_report", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_performance_report_create_time"))
        batch_op.drop_index(batch_op.f("ix_performance_report_case_id"))

    op.drop_table("performance_report")
    op.drop_table("batch_result")
    with op.batch_alter_table("ui_case", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ui_case_name"))
        batch_op.drop_index(batch_op.f("ix_ui_case_creator_id"))
        batch_op.drop_index(batch_op.f("ix_ui_case_create_time"))

    op.drop_table("ui_case")
    op.drop_table("test_task")
    with op.batch_alter_table("test_case", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_test_case_name"))
        batch_op.drop_index(batch_op.f("ix_test_case_module"))
        batch_op.drop_index(batch_op.f("ix_test_case_creator_id"))
        batch_op.drop_index(batch_op.f("ix_test_case_create_time"))

    op.drop_table("test_case")
    with op.batch_alter_table("sys_operation_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sys_operation_log_user_id"))
        batch_op.drop_index(batch_op.f("ix_sys_operation_log_operation"))
        batch_op.drop_index(batch_op.f("ix_sys_operation_log_operate_time"))

    op.drop_table("sys_operation_log")
    with op.batch_alter_table("performance_case", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_performance_case_name"))
        batch_op.drop_index(batch_op.f("ix_performance_case_creator_id"))
        batch_op.drop_index(batch_op.f("ix_performance_case_create_time"))

    op.drop_table("performance_case")
    op.drop_table("batch_task")
    with op.batch_alter_table("async_task", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_async_task_status"))
        batch_op.drop_index(batch_op.f("ix_async_task_creator_id"))

    op.drop_table("async_task")
    with op.batch_alter_table("ai_agent_task", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ai_agent_task_task_type"))
        batch_op.drop_index(batch_op.f("ix_ai_agent_task_creator_id"))

    op.drop_table("ai_agent_task")
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_role"))

    op.drop_table("user")
    # ### end Alembic commands ###
