"""add_testdataset_apicontract_retried_unstable

Revision ID: 9fe14fa34fc5
Revises: 4e38abe6bd09
Create Date: 2026-06-25 20:24:16.156604

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9fe14fa34fc5"
down_revision = "4e38abe6bd09"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_contract",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("endpoint", sa.String(length=500), nullable=False, comment="接口标识，如 GET /api/user/{id}"),
        sa.Column("summary", sa.String(length=200), nullable=True, comment="接口描述"),
        sa.Column("request_schema", sa.JSON(), nullable=True, comment="请求参数 Schema"),
        sa.Column("response_schema", sa.JSON(), nullable=True, comment="响应体 Schema"),
        sa.Column("schema_hash", sa.String(length=64), nullable=True, comment="Schema 的 SHA256，用于变更检测"),
        sa.Column("last_version", sa.Integer(), nullable=True, comment="契约版本号"),
        sa.Column("create_time", sa.DateTime(), nullable=True),
        sa.Column("update_time", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("api_contract", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_api_contract_endpoint"), ["endpoint"], unique=False)

    op.create_table(
        "test_data_set",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False, comment="数据集名称，如'注册-边界值'"),
        sa.Column("case_id", sa.Integer(), nullable=True, comment="绑定的用例模板"),
        sa.Column("data_rows", sa.Text(), nullable=True, comment='数据行，JSON 数组，如 [{"username":"a","pwd":"1"}]'),
        sa.Column("create_time", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["case_id"], ["test_case.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("test_data_set", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_test_data_set_case_id"), ["case_id"], unique=False)

    with op.batch_alter_table("test_case", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("unstable", sa.Boolean(), nullable=True, comment="不稳定用例标记：近5次执行中FLAKY>=3次")
        )

    with op.batch_alter_table("test_report", schema=None) as batch_op:
        batch_op.add_column(sa.Column("retried", sa.Integer(), nullable=True, comment="重试次数，0 表示第一次通过"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("test_report", schema=None) as batch_op:
        batch_op.drop_column("retried")

    with op.batch_alter_table("test_case", schema=None) as batch_op:
        batch_op.drop_column("unstable")

    with op.batch_alter_table("test_data_set", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_test_data_set_case_id"))

    op.drop_table("test_data_set")
    with op.batch_alter_table("api_contract", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_api_contract_endpoint"))

    op.drop_table("api_contract")
    # ### end Alembic commands ###
