"""add PerformanceBaseline

Revision ID: a0142297cd80
Revises: 3f992570278a
Create Date: 2026-06-01 08:42:10.506062

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a0142297cd80"
down_revision = "3f992570278a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "performance_baseline",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("case_id", sa.Integer(), nullable=True, comment="关联用例ID"),
        sa.Column("report_id", sa.Integer(), nullable=True, comment="基线来源报告ID"),
        sa.Column("p90", sa.Float(), nullable=True, comment="基线 P90（主判据）"),
        sa.Column("p99", sa.Float(), nullable=True, comment="基线 P99"),
        sa.Column("avg_time", sa.Float(), nullable=True, comment="基线平均耗时"),
        sa.Column("qps", sa.Float(), nullable=True, comment="基线 QPS"),
        sa.Column("create_time", sa.DateTime(), nullable=True, comment="基线创建时间"),
        sa.Column("update_time", sa.DateTime(), nullable=True, comment="基线更新时间"),
        sa.ForeignKeyConstraint(["case_id"], ["performance_case.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["report_id"], ["performance_report.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("performance_baseline", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_performance_baseline_case_id"), ["case_id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("performance_baseline", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_performance_baseline_case_id"))

    op.drop_table("performance_baseline")
    # ### end Alembic commands ###
