"""add_driver_type_browser_to_uicase

Revision ID: f331bbaf6f81
Revises: 7387db0d761e
Create Date: 2026-06-26 10:32:32.805831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f331bbaf6f81'
down_revision = '7387db0d761e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ui_case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('driver_type', sa.String(length=20), nullable=True, comment='驱动类型：local（本地）/ remote（Selenium Grid）'))
        batch_op.add_column(sa.Column('browser', sa.String(length=20), nullable=True, comment='浏览器：chrome / firefox / edge'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ui_case', schema=None) as batch_op:
        batch_op.drop_column('browser')
        batch_op.drop_column('driver_type')
    # ### end Alembic commands ###
